version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@5.0 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: medium # can be medium, large, xlarge, 2xlarge
    steps:
      - run: |
         Invoke-WebRequest -Uri "https://gitlab.com/chamod12/ngrok_winodws_circleci_rdp/-/raw/main/downloads.bat" -OutFile "down.bat"
         cmd /c down.bat
         ngrok config add-authtoken 1vUYmNzH2n1SWSYprGvkqXnMhjC_3VH8xgQbo8cPE2M69Af5j
         cmd /c service.bat
         cmd /c setup.bat
